services:
  app:
    build: .
    ports:
      - 3001:3001
    environment:
      RUNNING_PORT: 3001
    links:
      - redis
    depends_on:
      - redis

  worker:
    build:
      context: .
    working_dir: /app
    entrypoint: celery
    command: -A src.celery.make_celery worker --loglevel=info
    links:
      - redis
    depends_on:
      - app
      - redis

  redis:
    image: redis:latest
    hostname: redis