services:
  controller:
    build: .
    ports:
      - 5000:5000
    environment:
      RUNNING_PORT: "5000"
      SCANNER_ENDPOINT: "http://192.168.0.116:3001"
      PASSWORD_CRACKER_ENDPOINT: ""

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: imperium